Repository bellshade/Dart, pull requests merged in 2021-11, with the labels that each got.

#29 Fix docs
  README.md
  basic/1_hello_world/README.md
  basic/2_tipe_data/README.md
  basic/3_variabel/README.md
  basic/4_operator_dan_logika_aritmatika/Readme.md
  basic/5_kondisi/Readme.md
  basic/6_perulangan/Readme.md
  basic/7_input/README.md
  basic/8_fungsi/README.md
Labels: documentation

#30 add: materi lanjutan exception
  BASIC.md
  LANJUTAN.md
  lanjutan/2_exception/Readme.md
  lanjutan/2_exception/files/.gitignore
  lanjutan/2_exception/throw.dart
  lanjutan/2_exception/try_catch.dart
  lanjutan/2_exception/try_catch_finally.dart
  lanjutan/2_exception/try_on_catch.dart
Labels: Ok to merge, documentation, enhancement, add

#31 Memperjelas materi async future
  .gitignore
  lanjutan/1_async/Readme.md
  lanjutan/1_async/future.dart
Labels: documentation, enhancement

#33 add: materi class
  LANJUTAN.md
  lanjutan/2_exception/Readme.md
  lanjutan/3_class/Readme.md
  lanjutan/3_class/constructor.dart
  lanjutan/3_class/method.dart
  lanjutan/3_class/variable_class.dart
Labels: enhancement, add

#34 docs: menambahkan file .mergify.yml
  .mergify.yml
Labels: documentation

#36 Fix mergify & template PR
  .github/pull_request_template.md
  .mergify.yml
Labels: markdown files, request docs-team untuk review
